In [1]:
import pandas as pd

file_path = r"C:\Users\User\PycharmProjects\AISS-forest-restoration-project\data\raw\global_forest_watch_raw_data.xlsx"

xls = pd.ExcelFile(file_path)

xls.sheet_names

['Read_Me',
 'Country tree cover loss',
 'Country primary loss',
 'Country drivers',
 'Country carbon data',
 'Subnational 1 tree cover loss',
 'Subnational 1 primary loss',
 'Subnational 1 drivers',
 'Subnational 1 carbon data']

In [2]:
df_loss = pd.read_excel(
    file_path,
    sheet_name="Subnational 1 tree cover loss"
)

df_loss.head()

,country,subnational1,threshold,area_ha,extent_2000_ha,extent_2010_ha,gain_2000-2012_ha,tc_loss_ha_2001,tc_loss_ha_2002,tc_loss_ha_2003,...,tc_loss_ha_2015,tc_loss_ha_2016,tc_loss_ha_2017,tc_loss_ha_2018,tc_loss_ha_2019,tc_loss_ha_2020,tc_loss_ha_2021,tc_loss_ha_2022,tc_loss_ha_2023,tc_loss_ha_2024
0,Afghanistan,Badakhshan,0,4368996,4368996,4368996,403,3,9,1,...,0,0,0,0,0,0,0,0,4,7
1,Afghanistan,Badakhshan,10,4368996,10556,1763,403,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,Afghanistan,Badakhshan,15,4368996,3074,913,403,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Afghanistan,Badakhshan,20,4368996,2088,825,403,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Afghanistan,Badakhshan,25,4368996,1230,474,403,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df_loss.columns = (
    df_loss.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [4]:
df_loss.columns

Index(['country', 'subnational1', 'threshold', 'area_ha', 'extent_2000_ha',
       'extent_2010_ha', 'gain_2000-2012_ha', 'tc_loss_ha_2001',
       'tc_loss_ha_2002', 'tc_loss_ha_2003', 'tc_loss_ha_2004',
       'tc_loss_ha_2005', 'tc_loss_ha_2006', 'tc_loss_ha_2007',
       'tc_loss_ha_2008', 'tc_loss_ha_2009', 'tc_loss_ha_2010',
       'tc_loss_ha_2011', 'tc_loss_ha_2012', 'tc_loss_ha_2013',
       'tc_loss_ha_2014', 'tc_loss_ha_2015', 'tc_loss_ha_2016',
       'tc_loss_ha_2017', 'tc_loss_ha_2018', 'tc_loss_ha_2019',
       'tc_loss_ha_2020', 'tc_loss_ha_2021', 'tc_loss_ha_2022',
       'tc_loss_ha_2023', 'tc_loss_ha_2024'],
      dtype='str')

In [5]:
df_loss = df_loss[df_loss["threshold"] == 30].copy()

In [6]:
df_loss["threshold"].unique()

array([30])

In [7]:
df_loss.columns.tolist()

['country',
 'subnational1',
 'threshold',
 'area_ha',
 'extent_2000_ha',
 'extent_2010_ha',
 'gain_2000-2012_ha',
 'tc_loss_ha_2001',
 'tc_loss_ha_2002',
 'tc_loss_ha_2003',
 'tc_loss_ha_2004',
 'tc_loss_ha_2005',
 'tc_loss_ha_2006',
 'tc_loss_ha_2007',
 'tc_loss_ha_2008',
 'tc_loss_ha_2009',
 'tc_loss_ha_2010',
 'tc_loss_ha_2011',
 'tc_loss_ha_2012',
 'tc_loss_ha_2013',
 'tc_loss_ha_2014',
 'tc_loss_ha_2015',
 'tc_loss_ha_2016',
 'tc_loss_ha_2017',
 'tc_loss_ha_2018',
 'tc_loss_ha_2019',
 'tc_loss_ha_2020',
 'tc_loss_ha_2021',
 'tc_loss_ha_2022',
 'tc_loss_ha_2023',
 'tc_loss_ha_2024']

In [8]:
loss_cols = [col for col in df_loss.columns if col.startswith("tc_loss_ha_")]

df_loss = df_loss[
    ["country", "subnational1", "area_ha"] + loss_cols
].copy()

In [9]:
df_loss_long = df_loss.melt(
    id_vars=["country", "subnational1", "area_ha"],
    value_vars=loss_cols,
    var_name="year",
    value_name="loss_ha"
)

In [10]:
df_loss_long["year"] = (
    df_loss_long["year"]
    .str.replace("tc_loss_ha_", "")
    .astype(int)
)

In [11]:
df_loss_long.head(30)

        country subnational1  area_ha  year  loss_ha
0   Afghanistan   Badakhshan  4368996  2001        0
1   Afghanistan      Badghis  2058697  2001        5
2   Afghanistan      Baghlan  2112104  2001        1
3   Afghanistan        Balkh  1725362  2001        0
4   Afghanistan       Bamyan  1417319  2001        0
5   Afghanistan     Daykundi  1790706  2001        0
6   Afghanistan        Farah  4844254  2001        0
7   Afghanistan       Faryab  2029541  2001        1
8   Afghanistan       Ghazni  2291759  2001        0
9   Afghanistan         Ghor  3647005  2001        0
10  Afghanistan      Hilmand  5851432  2001        0
11  Afghanistan        Hirat  5473144  2001        0
12  Afghanistan      Jawzjan  1180162  2001        0
13  Afghanistan        Kabul   446459  2001        0
14  Afghanistan     Kandahar  5350896  2001        0
15  Afghanistan       Kapisa   190725  2001        0
16  Afghanistan        Khost   402071  2001        0
17  Afghanistan        Kunar   488919  2001        3
18  Afghanistan       Kunduz   804194  2001       49
19  Afghanistan      Laghman   384243  2001        0
20  Afghanistan        Logar   386967  2001        0
21  Afghanistan    Nangarhar   746779  2001        0
22  Afghanistan       Nimroz  4096676  2001        0
23  Afghanistan     Nuristan   922441  2001        3
24  Afghanistan      Paktika  1906111  2001        0
25  Afghanistan       Paktya   642920  2001        0
26  Afghanistan     Panjshir   363551  2001        0
27  Afghanistan       Parwan   588867  2001        0
28  Afghanistan     Samangan  1126363  2001        6
29  Afghanistan     Sari Pul  1600068  2001        0

In [12]:
df_loss_long = df_loss_long.rename(columns={
    "subnational1": "region"
})

In [13]:
df_loss_long.head()

       country      region  area_ha  year  loss_ha
0  Afghanistan  Badakhshan  4368996  2001        0
1  Afghanistan     Badghis  2058697  2001        5
2  Afghanistan     Baghlan  2112104  2001        1
3  Afghanistan       Balkh  1725362  2001        0
4  Afghanistan      Bamyan  1417319  2001        0

In [14]:
df_loss_long["region"] = (
    df_loss_long["region"]
    .str.strip()
    .str.replace(r"^[^a-zA-Z]+", "", regex=True)  # remove leading symbols
)

In [15]:
df_loss_long = df_loss_long[
    df_loss_long["region"] != ""
].copy()

In [16]:
df_loss_long["region"].unique()[:10]

<StringArray>
['Badakhshan',    'Badghis',    'Baghlan',      'Balkh',     'Bamyan',
   'Daykundi',      'Farah',     'Faryab',     'Ghazni',       'Ghor']
Length: 10, dtype: str

In [17]:
df_loss_long["loss_ha"].describe()

count    6.840000e+04
mean     7.555408e+03
std      4.978316e+04
min      0.000000e+00
25%      1.600000e+01
50%      2.930000e+02
75%      2.266000e+03
max      4.541332e+06
Name: loss_ha, dtype: float64

In [18]:
df_test = df_loss_long[df_loss_long["country"] == "Portugal"].copy()

In [19]:
df_test["land_loss_pct"] = df_test["loss_ha"] / df_test["area_ha"]

In [20]:
df_test[df_test["region"] == "Porto"].sort_values("year")

        country region  area_ha  year  loss_ha  land_loss_pct
1854   Portugal  Porto   232960  2001      584       0.002507
4705   Portugal  Porto   232960  2002     1095       0.004700
7556   Portugal  Porto   232960  2003      313       0.001344
10407  Portugal  Porto   232960  2004     1226       0.005263
13258  Portugal  Porto   232960  2005     1332       0.005718
16109  Portugal  Porto   232960  2006     1485       0.006374
18960  Portugal  Porto   232960  2007     1262       0.005417
21811  Portugal  Porto   232960  2008     1300       0.005580
24662  Portugal  Porto   232960  2009     1565       0.006718
27513  Portugal  Porto   232960  2010     1917       0.008229
30364  Portugal  Porto   232960  2011      785       0.003370
33215  Portugal  Porto   232960  2012     1968       0.008448
36066  Portugal  Porto   232960  2013     3093       0.013277
38917  Portugal  Porto   232960  2014     3797       0.016299
41768  Portugal  Porto   232960  2015     1720       0.007383
44619  Portugal  Porto   232960  2016     4727       0.020291
47470  Portugal  Porto   232960  2017     3750       0.016097
50321  Portugal  Porto   232960  2018     2984       0.012809
53172  Portugal  Porto   232960  2019     1775       0.007619
56023  Portugal  Porto   232960  2020     2339       0.010040
58874  Portugal  Porto   232960  2021     1621       0.006958
61725  Portugal  Porto   232960  2022     2219       0.009525
64576  Portugal  Porto   232960  2023     1508       0.006473
67427  Portugal  Porto   232960  2024     3369       0.014462

In [21]:
df_loss_long.shape

(68400, 5)

In [22]:
df_carbon = pd.read_excel(
    file_path,
    sheet_name="Subnational 1 carbon data"
)

df_carbon.head()

,country,subnational1,umd_tree_cover_density_2000__threshold,umd_tree_cover_extent_2000__ha,gfw_aboveground_carbon_stocks_2000__Mg_C,avg_gfw_aboveground_carbon_stocks_2000__Mg_C_ha-1,gfw_forest_carbon_gross_emissions__Mg_CO2e_yr-1,gfw_forest_carbon_gross_removals__Mg_CO2_yr-1,gfw_forest_carbon_net_flux__Mg_CO2e_yr-1,gfw_forest_carbon_gross_emissions_2001__Mg_CO2e,...,gfw_forest_carbon_gross_emissions_2015__Mg_CO2e,gfw_forest_carbon_gross_emissions_2016__Mg_CO2e,gfw_forest_carbon_gross_emissions_2017__Mg_CO2e,gfw_forest_carbon_gross_emissions_2018__Mg_CO2e,gfw_forest_carbon_gross_emissions_2019__Mg_CO2e,gfw_forest_carbon_gross_emissions_2020__Mg_CO2e,gfw_forest_carbon_gross_emissions_2021__Mg_CO2e,gfw_forest_carbon_gross_emissions_2022__Mg_CO2e,gfw_forest_carbon_gross_emissions_2023__Mg_CO2e,gfw_forest_carbon_gross_emissions_2024__Mg_CO2e
0,Afghanistan,Badakhshan,30,1054,49680,47,40,5999,-5959,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,Badakhshan,50,278,13809,50,13,2049,-2036,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,Badakhshan,75,27,1721,65,3,766,-763,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Badghis,30,516,27974,54,111,955,-843,1472.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Badghis,50,335,18833,56,103,650,-548,1443.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
df_carbon.columns.tolist()

['country',
 'subnational1',
 'umd_tree_cover_density_2000__threshold',
 'umd_tree_cover_extent_2000__ha',
 'gfw_aboveground_carbon_stocks_2000__Mg_C',
 'avg_gfw_aboveground_carbon_stocks_2000__Mg_C_ha-1',
 'gfw_forest_carbon_gross_emissions__Mg_CO2e_yr-1',
 'gfw_forest_carbon_gross_removals__Mg_CO2_yr-1',
 'gfw_forest_carbon_net_flux__Mg_CO2e_yr-1',
 'gfw_forest_carbon_gross_emissions_2001__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2002__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2003__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2004__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2005__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2006__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2007__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2008__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2009__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2010__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2011__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2012__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2013__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2014__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2015__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2016__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2017__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2018__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2019__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2020__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2021__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2022__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2023__Mg_CO2e',
 'gfw_forest_carbon_gross_emissions_2024__Mg_CO2e']

In [24]:
emission_cols = [
    col for col in df_carbon.columns
    if col.startswith("gfw_forest_carbon_gross_emissions_")
    and "__Mg_CO2e" in col
]

df_carbon = df_carbon[
    ["country", "subnational1"] + emission_cols
].copy()

In [25]:
len(emission_cols)

25

In [26]:
emission_cols = [
    col for col in df_carbon.columns
    if col.startswith("gfw_forest_carbon_gross_emissions_20")
]

In [27]:
len(emission_cols)

24

In [28]:
df_carbon_long = df_carbon.melt(
    id_vars=["country", "subnational1"],
    value_vars=emission_cols,
    var_name="year",
    value_name="carbon_emissions"
)

In [29]:
df_carbon_long["year"] = (
    df_carbon_long["year"]
    .str.replace("gfw_forest_carbon_gross_emissions_", "")
    .str.replace("__Mg_CO2e", "")
    .astype(int)
)

In [30]:
df_carbon_long.head(20)

        country subnational1  year  carbon_emissions
0   Afghanistan   Badakhshan  2001               0.0
1   Afghanistan   Badakhshan  2001               0.0
2   Afghanistan   Badakhshan  2001               0.0
3   Afghanistan      Badghis  2001            1472.0
4   Afghanistan      Badghis  2001            1443.0
5   Afghanistan      Badghis  2001            1178.0
6   Afghanistan      Baghlan  2001             126.0
7   Afghanistan      Baghlan  2001             105.0
8   Afghanistan      Baghlan  2001              35.0
9   Afghanistan        Balkh  2001               0.0
10  Afghanistan        Balkh  2001               0.0
11  Afghanistan        Balkh  2001               0.0
12  Afghanistan       Bamyan  2001               0.0
13  Afghanistan       Bamyan  2001               0.0
14  Afghanistan       Bamyan  2001               0.0
15  Afghanistan     Daykundi  2001               0.0
16  Afghanistan     Daykundi  2001               0.0
17  Afghanistan     Daykundi  2001               0.0
18  Afghanistan        Farah  2001               0.0
19  Afghanistan        Farah  2001               0.0

In [31]:
df_carbon.columns

Index(['country', 'subnational1',
       'gfw_forest_carbon_gross_emissions__Mg_CO2e_yr-1',
       'gfw_forest_carbon_gross_emissions_2001__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2002__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2003__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2004__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2005__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2006__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2007__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2008__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2009__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2010__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2011__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2012__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2013__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2014__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2015__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2016__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2017__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2018__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2019__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2020__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2021__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2022__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2023__Mg_CO2e',
       'gfw_forest_carbon_gross_emissions_2024__Mg_CO2e'],
      dtype='str')

In [32]:
df_carbon = pd.read_excel(
    file_path,
    sheet_name="Subnational 1 carbon data"
)

# filter threshold FIRST
df_carbon = df_carbon[
    df_carbon["umd_tree_cover_density_2000__threshold"] == 30
].copy()

In [33]:
emission_cols = [
    col for col in df_carbon.columns
    if col.startswith("gfw_forest_carbon_gross_emissions_20")
]

df_carbon = df_carbon[
    ["country", "subnational1"] + emission_cols
].copy()

In [34]:
df_carbon_long = df_carbon.melt(
    id_vars=["country", "subnational1"],
    value_vars=emission_cols,
    var_name="year",
    value_name="carbon_emissions"
)

In [35]:
df_carbon_long["year"] = (
    df_carbon_long["year"]
    .str.replace("gfw_forest_carbon_gross_emissions_", "")
    .str.replace("__Mg_CO2e", "")
    .astype(int)
)

In [36]:
df_carbon_long.head()

       country subnational1  year  carbon_emissions
0  Afghanistan   Badakhshan  2001               0.0
1  Afghanistan      Badghis  2001            1472.0
2  Afghanistan      Baghlan  2001             126.0
3  Afghanistan        Balkh  2001               0.0
4  Afghanistan       Bamyan  2001               0.0

In [38]:
df_carbon_long["year"].unique()[:24]

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024])

In [39]:
df_carbon_long.shape

(68424, 4)

In [40]:
df_carbon_long["year"].nunique()

24

In [41]:
df_carbon_long = df_carbon_long.rename(columns={
    "subnational1": "region"
})

In [42]:
df_loss_long.columns

Index(['country', 'region', 'area_ha', 'year', 'loss_ha'], dtype='str')

In [43]:
df_loss_long["land_loss_pct"] = (
    df_loss_long["loss_ha"] / df_loss_long["area_ha"]
)

In [44]:
df_loss_long.columns

Index(['country', 'region', 'area_ha', 'year', 'loss_ha', 'land_loss_pct'], dtype='str')

In [45]:
df_loss_long["land_loss_pct"].max()

np.float64(0.24196879545714783)

In [46]:
df_loss_long[
    df_loss_long["land_loss_pct"] > 0.2
].sort_values("land_loss_pct", ascending=False).head()

,country,region,area_ha,year,loss_ha,land_loss_pct
54306,Australia,Australian Capital Territory,235799,2020,57056,0.241969

In [48]:
df_test = df_loss_long[
    (df_loss_long["country"] == "Peru") &
    (df_loss_long["region"] == "Ucayali")
].sort_values("year")

df_test

      country   region   area_ha  year  loss_ha  land_loss_pct
1744     Peru  Ucayali  10507766  2001    13205       0.001257
4595     Peru  Ucayali  10507766  2002    12734       0.001212
7446     Peru  Ucayali  10507766  2003    13192       0.001255
10297    Peru  Ucayali  10507766  2004    12700       0.001209
13148    Peru  Ucayali  10507766  2005    29461       0.002804
15999    Peru  Ucayali  10507766  2006    15611       0.001486
18850    Peru  Ucayali  10507766  2007    11658       0.001109
21701    Peru  Ucayali  10507766  2008    22891       0.002178
24552    Peru  Ucayali  10507766  2009    33541       0.003192
27403    Peru  Ucayali  10507766  2010    20439       0.001945
30254    Peru  Ucayali  10507766  2011    26782       0.002549
33105    Peru  Ucayali  10507766  2012    43899       0.004178
35956    Peru  Ucayali  10507766  2013    51166       0.004869
38807    Peru  Ucayali  10507766  2014    41743       0.003973
41658    Peru  Ucayali  10507766  2015    33285       0.003168
44509    Peru  Ucayali  10507766  2016    44692       0.004253
47360    Peru  Ucayali  10507766  2017    56429       0.005370
50211    Peru  Ucayali  10507766  2018    35719       0.003399
53062    Peru  Ucayali  10507766  2019    53034       0.005047
55913    Peru  Ucayali  10507766  2020    62950       0.005991
58764    Peru  Ucayali  10507766  2021    52084       0.004957
61615    Peru  Ucayali  10507766  2022    53095       0.005053
64466    Peru  Ucayali  10507766  2023    49956       0.004754
67317    Peru  Ucayali  10507766  2024    55703       0.005301

In [49]:
df_final = df_loss_long.merge(
    df_carbon_long,
    on=["country", "region", "year"],
    how="inner"
)

In [50]:
df_final.shape

(67392, 7)

In [51]:
df_final.columns

Index(['country', 'region', 'area_ha', 'year', 'loss_ha', 'land_loss_pct',
       'carbon_emissions'],
      dtype='str')

In [52]:
df_final[["country", "region", "year"]].duplicated().sum()

np.int64(96)

In [53]:
df_final[
    df_final[["country", "region", "year"]].duplicated(keep=False)
].sort_values(["country", "region", "year"]).head(20)

       country region  area_ha  year  loss_ha  land_loss_pct  carbon_emissions
177    Belarus  Minsk  3779627  2001     3744       0.000991         1039839.0
178    Belarus  Minsk  3779627  2001     3744       0.000991           36475.0
179    Belarus  Minsk   225998  2001      121       0.000535         1039839.0
180    Belarus  Minsk   225998  2001      121       0.000535           36475.0
2985   Belarus  Minsk  3779627  2002     5951       0.001574         1642325.0
2986   Belarus  Minsk  3779627  2002     5951       0.001574           73334.0
2987   Belarus  Minsk   225998  2002      229       0.001013         1642325.0
2988   Belarus  Minsk   225998  2002      229       0.001013           73334.0
5793   Belarus  Minsk  3779627  2003     6411       0.001696         1880598.0
5794   Belarus  Minsk  3779627  2003     6411       0.001696           43569.0
5795   Belarus  Minsk   225998  2003      144       0.000637         1880598.0
5796   Belarus  Minsk   225998  2003      144       0.000637           43569.0
8601   Belarus  Minsk  3779627  2004     7585       0.002007         2316605.0
8602   Belarus  Minsk  3779627  2004     7585       0.002007           75687.0
8603   Belarus  Minsk   225998  2004      228       0.001009         2316605.0
8604   Belarus  Minsk   225998  2004      228       0.001009           75687.0
11409  Belarus  Minsk  3779627  2005     6660       0.001762         2071821.0
11410  Belarus  Minsk  3779627  2005     6660       0.001762           70980.0
11411  Belarus  Minsk   225998  2005      218       0.000965         2071821.0
11412  Belarus  Minsk   225998  2005      218       0.000965           70980.0

In [55]:
df_carbon_long = df_carbon_long.drop_duplicates(
    subset=["country", "region", "year"]
)

In [56]:
df_final = df_loss_long.merge(
    df_carbon_long,
    on=["country", "region", "year"],
    how="inner"
)

In [57]:
df_final[["country", "region", "year"]].duplicated().sum()

np.int64(24)

In [58]:
df_loss_long[["country", "region", "year"]].duplicated().sum()

np.int64(24)

In [59]:
df_carbon_long[["country", "region", "year"]].duplicated().sum()

np.int64(0)

In [61]:
df_carbon_long[["country", "region", "year"]].duplicated().sum()

np.int64(0)

In [62]:
df_loss_long["region"] = df_loss_long["region"].str.strip().str.lower()
df_carbon_long["region"] = df_carbon_long["region"].str.strip().str.lower()

df_loss_long["country"] = df_loss_long["country"].str.strip().str.lower()
df_carbon_long["country"] = df_carbon_long["country"].str.strip().str.lower()

In [63]:
df_final = df_loss_long.merge(
    df_carbon_long,
    on=["country", "region", "year"],
    how="inner"
)

In [64]:
df_final[["country", "region", "year"]].duplicated().sum()

np.int64(24)

In [65]:
dupes = df_final[
    df_final[["country", "region", "year"]].duplicated(keep=False)
].sort_values(["country", "region", "year"])

dupes.head(20)

       country region  area_ha  year  loss_ha  land_loss_pct  carbon_emissions
177    belarus  minsk  3779627  2001     3744       0.000991         1039839.0
178    belarus  minsk   225998  2001      121       0.000535         1039839.0
2982   belarus  minsk  3779627  2002     5951       0.001574         1642325.0
2983   belarus  minsk   225998  2002      229       0.001013         1642325.0
5787   belarus  minsk  3779627  2003     6411       0.001696         1880598.0
5788   belarus  minsk   225998  2003      144       0.000637         1880598.0
8592   belarus  minsk  3779627  2004     7585       0.002007         2316605.0
8593   belarus  minsk   225998  2004      228       0.001009         2316605.0
11397  belarus  minsk  3779627  2005     6660       0.001762         2071821.0
11398  belarus  minsk   225998  2005      218       0.000965         2071821.0
14202  belarus  minsk  3779627  2006    10061       0.002662         3180134.0
14203  belarus  minsk   225998  2006      868       0.003841         3180134.0
17007  belarus  minsk  3779627  2007     6429       0.001701         2067829.0
17008  belarus  minsk   225998  2007      292       0.001292         2067829.0
19812  belarus  minsk  3779627  2008     7805       0.002065         2573857.0
19813  belarus  minsk   225998  2008      298       0.001319         2573857.0
22617  belarus  minsk  3779627  2009     8228       0.002177         2818466.0
22618  belarus  minsk   225998  2009      268       0.001186         2818466.0
25422  belarus  minsk  3779627  2010     8257       0.002185         2892347.0
25423  belarus  minsk   225998  2010      400       0.001770         2892347.0

In [66]:
df_carbon_long = df_carbon_long.groupby(
    ["country", "region", "year"],
    as_index=False
)["carbon_emissions"].sum()

In [67]:
df_final = df_loss_long.merge(
    df_carbon_long,
    on=["country", "region", "year"],
    how="inner"
)

In [68]:
df_final[["country", "region", "year"]].duplicated().sum()

np.int64(24)

In [71]:
dupes = df_final[
    df_final[["country", "region", "year"]].duplicated(keep=False)
]

dupes[["country", "region", "year"]].drop_duplicates().head(20)

       country region  year
177    belarus  minsk  2001
2982   belarus  minsk  2002
5787   belarus  minsk  2003
8592   belarus  minsk  2004
11397  belarus  minsk  2005
14202  belarus  minsk  2006
17007  belarus  minsk  2007
19812  belarus  minsk  2008
22617  belarus  minsk  2009
25422  belarus  minsk  2010
28227  belarus  minsk  2011
31032  belarus  minsk  2012
33837  belarus  minsk  2013
36642  belarus  minsk  2014
39447  belarus  minsk  2015
42252  belarus  minsk  2016
45057  belarus  minsk  2017
47862  belarus  minsk  2018
50667  belarus  minsk  2019
53472  belarus  minsk  2020

In [72]:
df_loss_long = df_loss_long.groupby(
    ["country", "region", "year"],
    as_index=False
).agg({
    "area_ha": "first",   # area is constant
    "loss_ha": "sum",
    "land_loss_pct": "sum"  # safe because it's derived from loss
})

In [73]:
df_carbon_long = df_carbon_long.groupby(
    ["country", "region", "year"],
    as_index=False
)["carbon_emissions"].sum()

In [74]:
df_final = df_loss_long.merge(
    df_carbon_long,
    on=["country", "region", "year"],
    how="inner"
)

In [75]:
df_final[["country", "region", "year"]].duplicated().sum()

np.int64(0)

In [76]:
df_loss_long["land_loss_pct"] = (
    df_loss_long["loss_ha"] / df_loss_long["area_ha"]
)

In [82]:
df_check = df_final[
    (df_final["country"] == "portugal") &
    (df_final["region"].isin(["porto"]))
].sort_values(["region", "year"])

df_check

,country,region,year,area_ha,loss_ha,land_loss_pct,carbon_emissions
43896,portugal,porto,2001,232960,584,0.002507,184981.0
43897,portugal,porto,2002,232960,1095,0.004700,328343.0
43898,portugal,porto,2003,232960,313,0.001344,103750.0
43899,portugal,porto,2004,232960,1226,0.005263,419024.0
43900,portugal,porto,2005,232960,1332,0.005718,397395.0
43901,portugal,porto,2006,232960,1485,0.006374,511150.0
43902,portugal,porto,2007,232960,1262,0.005417,499422.0
43903,portugal,porto,2008,232960,1300,0.005580,530624.0
43904,portugal,porto,2009,232960,1565,0.006718,596319.0
43905,portugal,porto,2010,232960,1917,0.008229,759836.0
43906,portugal,porto,2011,232960,785,0.003370,318397.0
43907,portugal,porto,2012,232960,1968,0.008448,776489.0
43908,portugal,porto,2013,232960,3093,0.013277,861696.0
43909,portugal,porto,2014,232960,3797,0.016299,1242772.0
43910,portugal,porto,2015,232960,1720,0.007383,696607.0
43911,portugal,porto,2016,232960,4727,0.020291,1531014.0
43912,portugal,porto,2017,232960,3750,0.016097,1257762.0
43913,portugal,porto,2018,232960,2984,0.012809,1253283.0
43914,portugal,porto,2019,232960,1775,0.007619,755944.0
43915,portugal,porto,2020,232960,2339,0.010040,986259.0
43916,portugal,porto,2021,232960,1621,0.006958,766452.0
43917,portugal,porto,2022,232960,2219,0.009525,823203.0
43918,portugal,porto,2023,232960,1508,0.006473,734528.0
43919,portugal,porto,2024,232960,3369,0.014462,1146807.0

In [83]:
output_path = r"C:\Users\User\PycharmProjects\AISS-forest-restoration-project\data\processed\subnational_clean.json"

df_final.to_json(output_path, orient="records")

In [84]:
import os
os.path.exists(output_path)

True